const KEY='study-companion-theme';
const THEMES=['system','light','dark'];
const mq=window.matchMedia?.('(prefers-color-scheme: dark)');

function savedTheme(){const v=localStorage.getItem(KEY);return THEMES.includes(v)?v:'system'}
function resolvedTheme(v=savedTheme()){return v==='system'?(mq?.matches?'dark':'light'):v}
function setTheme(value,{save=true}={}){if(!THEMES.includes(value))value='system';if(save)localStorage.setItem(KEY,value);const resolved=resolvedTheme(value);document.documentElement.dataset.theme=resolved;document.documentElement.dataset.themePreference=value;document.documentElement.style.colorScheme=resolved;const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=resolved==='dark'?'#171717':'#fbfbfa';document.querySelectorAll('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===value))}

function installStyles(){if(document.getElementById('sc-theme-styles'))return;const s=document.createElement('style');s.id='sc-theme-styles';s.textContent=`
:root{--sc-bg:#fbfbfa;--sc-surface:#fff;--sc-surface2:#f4f4f1;--sc-ink:#252525;--sc-muted:#777;--sc-line:#e7e7e3;--sc-link:#2f6f9f;--sc-active:#eaf2f8;--sc-active-border:#b9cfdf;--sc-active-ink:#245d87;--sc-shadow:#0002}
html[data-theme="dark"]{--sc-bg:#171717;--sc-surface:#202020;--sc-surface2:#292929;--sc-ink:#e8e8e5;--sc-muted:#aaa9a5;--sc-line:#393936;--sc-link:#7db4dc;--sc-active:#253746;--sc-active-border:#42647c;--sc-active-ink:#a9d1ef;--sc-shadow:#0007}
html,body{background:var(--sc-bg)!important;color:var(--sc-ink)!important}
.top{background:color-mix(in srgb,var(--sc-bg) 94%,transparent)!important;border-color:var(--sc-line)!important}.title,.word,.panel,.panel h1,.panel h2,.panel h3,.panel p,.panel li,.orig,.translit,.drawer,.drawerhead,.drawerbody,.annotation .body,.quote-text,.quote-topic{color:var(--sc-ink)!important}.back,.copy,.studybtn,.ref,.panel a,.quote-source a,.help-source a{color:var(--sc-link)!important}
.tab,.drawer,.field input,.field textarea,.field select,.menu-nav button,.quote-browse button,.facet-back,.facet-list button{background:var(--sc-surface)!important;color:var(--sc-ink)!important;border-color:var(--sc-line)!important}.tab.active,.menu-nav button.active,.quote-browse button.active{background:var(--sc-active)!important;border-color:var(--sc-active-border)!important;color:var(--sc-active-ink)!important}.panel,.drawerhead,.linkrow,.translation,.langentry,.helpentry,.annotation,.quote-card,.facet-list button{border-color:var(--sc-line)!important}.sourcebox{border-color:color-mix(in srgb,var(--sc-ink) 22%,transparent)!important}.status,.empty,.meta,.loading,.authmsg,.quote-category,.quote-meta,.quote-status,.quote-summary,.annotation .atype{color:var(--sc-muted)!important}.secondary,.pill,.quote-pills span,.quote-load{background:var(--sc-surface2)!important;color:var(--sc-ink)!important;border-color:var(--sc-line)!important}.close{color:var(--sc-muted)!important}.drawer{box-shadow:-8px 0 28px var(--sc-shadow)!important}
html[data-theme="dark"] .highlight-yellow{background:#6b5b17!important;color:#fff!important}html[data-theme="dark"] .highlight-blue{background:#244b68!important;color:#fff!important}html[data-theme="dark"] .highlight-green{background:#315a35!important;color:#fff!important}html[data-theme="dark"] .highlight-pink{background:#6a3449!important;color:#fff!important}
.theme-section{margin:18px 0 4px;padding-top:16px;border-top:1px solid var(--sc-line)}.theme-label{font-size:12px;font-weight:700;margin-bottom:8px;color:var(--sc-muted)}.theme-control{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;background:var(--sc-surface2);padding:4px;border-radius:10px}.theme-control button{border:0;border-radius:7px;background:transparent;color:var(--sc-muted);padding:8px 5px;font:600 12px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;cursor:pointer}.theme-control button.active{background:var(--sc-surface);color:var(--sc-ink);box-shadow:0 1px 4px var(--sc-shadow)}
`;document.head.appendChild(s)}

function installControl(){const body=document.querySelector('.drawerbody');if(!body||document.getElementById('themeSection'))return false;const box=document.createElement('section');box.id='themeSection';box.className='theme-section';box.innerHTML='<div class="theme-label">Appearance</div><div class="theme-control" role="group" aria-label="Appearance"><button data-theme-choice="light">☀︎ Light</button><button data-theme-choice="dark">☾ Dark</button><button data-theme-choice="system">System</button></div>';body.appendChild(box);box.querySelectorAll('[data-theme-choice]').forEach(b=>b.addEventListener('click',()=>setTheme(b.dataset.themeChoice)));setTheme(savedTheme(),{save:false});return true}

installStyles();setTheme(savedTheme(),{save:false});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installControl);else installControl();new MutationObserver(()=>installControl()).observe(document.documentElement,{childList:true,subtree:true});mq?.addEventListener?.('change',()=>{if(savedTheme()==='system')setTheme('system',{save:false})});
